#! /usr/bin/perl
use Getopt::Long;
use File::Spec;
use File::Path;
use File::Copy;
use Cwd;
use LWP::Simple;
use CDDB::File;

@genres = qw(blues, classical, country, data, folk, jazz, misc, newage, reggae, rock, soundtrack);

$freeDBURL = "http://www.freedb.org/freedb/";
$freeDBGenre = "rock";

$discid = $ARGV[0] || die "No DISCID specified\n";
$dest   = $ARGV[1] || die "No destination specified\n";

$discid =~ tr/A-Z/a-z/;
$udiscid = $discid;
$udiscid =~ tr/a-z/A-Z/;

$destdir = "abcde.$discid";
$destpath = File::Spec->join($dest, $destdir);

$freeDBReq = "$freeDBURL/$freeDBGenre/$discid";
$freeDBcontent = get($freeDBReq) || die "Could not retrieve $freeDBReq\n";
# print $freeDBcontent;

mkpath ($destpath) || die "Could not create $destpath\n";
$status   = File::Spec->join($destpath, "status");
$paranoia = File::Spec->join($destpath, "cdparanoia-audio-tracks");
$cddbread = File::Spec->join($destpath, "cddbread.1");
$cddiscid = File::Spec->join($destpath, "discid");

open STATUS,  "> $status" || die "Could not open $status\n";
open PARANOIA,  "> $paranoia" || die "Could not open $paranoia\n";
open CDDBREAD,  "> $cddbread" || die "Could not open $cddbread\n";
open CDDISCID,  "> $cddiscid" || die "Could not open $cddiscid\n";

print CDDBREAD $freeDBcontent, "\n";
close CDDBREAD;

my $cddb = CDDB::File->new($cddbread);

print CDDISCID $cddb->id(), " ", $cddb->track_count();
foreach $offset ($cddb->_offsets()) {
    print CDDISCID " $offset";
}
print CDDISCID "\n";
close CDDISCID;

print PARANOIA $cddb->track_count(), "\n";
close PARANOIA;

print STATUS "cdparanoia-audio-tracks\n";

$filesMoved = 0;
foreach $i (1 .. $cddb->track_count()) {
    $i = "0$i" if ($i < 10);
    move("$udiscid-track$i.wav", File::Spec->join($destpath, "track$i.wav")) || next;
    $filesMoved++;
    print STATUS "readtrack-$i\n";
}
print STATUS "encode-output=loud\n" if ($filesMoved == $cddb->track_count());

close STATUS;
