#! /usr/bin/perl
use Unicode::String;

while (<>)
{
    chomp;

    print "ARTIST=", Unicode::String::latin1($1)->utf8(), "\n" 		if (/TPE1.*:\s*(\w.*)\s*$/);
    print "ALBUM=", Unicode::String::latin1($1)->utf8(), "\n" 		if (/TALB.*:\s*(\w.*)\s*$/);
    print "TITLE=", Unicode::String::latin1($1)->utf8(), "\n" 		if (/TIT2.*:\s*(\w.*)\s*$/);
    print "DATE=", Unicode::String::latin1($1)->utf8(), "\n" 		if (/TYER.*:\s*(\w.*)\s*$/);
    print "GENRE=", Unicode::String::latin1($1)->utf8(), "\n" 		if (/TCON.*:\s*(\w.*)\s*\(.*\)\s*$/);
    print "TRACKNUMBER=", Unicode::String::latin1($1)->utf8(), "\n" 	if (/TRCK.*:\s*(\w.*)\s*$/);
    print "CDDB=", Unicode::String::latin1($1)->utf8(), "\n" 		if (/TXXX.*:.*CDDB.*:\s*(\w.*)\s*$/);
}
