#! /usr/bin/perl

use File::Spec;
use File::Path;

push @ARGV, "." if (@ARGV == 0);

foreach $i (@ARGV) {
    $dirSize = prune($i) if (-d $i);
    if ($dirSize == 0 && $i ne ".") { rmtree($i); }
}

sub prune {
    my $dir = shift;
    return 1 unless (-d $dir);
    opendir DIR, $dir || return 1;
    my @files = File::Spec->no_upwards(readdir DIR);
    closedir DIR;

    my $numFiles = @files;
    print "Pruning $dir\n";

    if ($numFiles == 0) { return 0; }
    foreach my $file (@files) {
	my $path = File::Spec->join($dir, $file);
	if (-d $path) {
	    if (prune ($path) == 0) {
		print "Deleting empty directory: $path\n";
		rmtree($path);
		$numFiles --;
	    }
	}
    }
    return $numFiles;
}
