#! /usr/bin/perl

use File::Spec;
use File::Path;
use Term::ANSIColor;
use Getopt::Long;

@deleteable      = ();
$dryRun          = 0;
$macFiles        = 0;
$help            = 0;
$verbose         = 0;


$result = GetOptions(
                     "delete=s"   =>    \@deleteable,
                     "M|mac!"     =>    \$macFiles,
                     "N|keep!"    =>    \$dryRun,
                     "v|verbose"  =>    \$verbose,
                     "help"       =>    \$help,
                     );

showusage() if $help;

push @ARGV, "." if (@ARGV == 0);

makeHash(@deleteable);

foreach $i (@ARGV) {
    $dirSize = prune($i) if (-d $i);
    if ($dirSize == 0 && $i ne ".") { rmtree($i); }
}

sub prune {
    my $dir = shift;
    return 1 unless (-d $dir);
    opendir DIR, $dir || return 1;
    my @files = File::Spec->no_upwards(readdir DIR);
    closedir DIR;

    my $numFiles = @files;
    print "Pruning $dir\n" if $verbose;

    if ($numFiles == 0) { return 0; }
    foreach my $file (@files) {
        my $path = File::Spec->join($dir, $file);
        if (-d $path) {
            if (prune ($path) == 0) {
                print color 'bold blue';
                print "Deleting empty directory: $path\n";
                print color 'reset';
                rmtree($path) unless $dryRun;
                $numFiles --;
            }
        }
    }
    # Count the number of files left which can be deleted.
    my $numDelete = countDeletable(@files);
    # Match it with what's there.
    return ($numFiles - $numDelete);
}

sub countDeletable {
    my $count = 0;
    foreach my $file (@_) {
        if (exists $delete{$file}) {
            $count++
        } elsif ($macFiles && ($file =~ /^\._.*/)) {
            $count++
        }
    }
    return $count;
}

sub makeHash {
    foreach my $file (@_) {
        $delete{$file} = 1;
    }
}

sub showusage {
    print <<"EOT";
Usage: $0 [--delete file] [--mac] [--dryrun] [--verbose] [--help] directories
        --delete|-d file        Delete files with this name as well.   Can be repeated.
        --mac|-M                Delete Mac files that start with ._
        --dryrun|-N             Don't actually delete anything, just list what's being deleted.
        --verbose|-v            List all directories as they're processed
        --help|-h               Show this help.
        directories             List of directories to prune.   If none are listed, . is used.
EOT
    exit 0;
}
