#! /usr/bin/perl
use File::Spec;
use File::Path;

foreach $i (@ARGV) {
    $dirSize = setGain($i) if (-d $i);
}

sub setGain {
    my $dir = shift;
    return 1 unless (-d $dir);
    opendir DIR, $dir || return 1;
    my @files = File::Spec->no_upwards(readdir DIR);
    closedir DIR;

    my @mp3s = ();
    print "Checking $dir\n";

    foreach my $file (@files) {
	my $path = File::Spec->join($dir, $file);
	if (-d $path) {
	    setGain ($path);
	} elsif ($file =~ /.*\.mp3$/) {
	    push @mp3s, $path;
	}
    }
    if (@mp3s != 0) {
	print "Setting mp3gain in $dir\n";
	system("mp3gain", "-k", "-a", @mp3s);
    }
}
